### ISSUE TITLE
Get query responce format

### ISSUE THREAD

**Issue by tehnar** [java-course-au/assignments-2#52]
@dzharkov

Не кажется ли логичным, чтобы нам в ответ присылали не просто некоторый массив байт, а еще и его размер?
Количество байт, переданное нам, может быть меньше размера части, если она является последней для файла. Можно, конечно, как-то это обрабатывать руками, но это кажется неудобным.
Еще одна проблема -- в таком варианте запрос get неявно предполагает, что клиент имеет в наличии нужную часть. Если же этой части нет, то совершенно непонятно, что клиент должен ответить. Можно конечно запретить делать такие запросы, но тогда, кажется, следует указать в формулировке задания, что делать в случае, если пришел такой неправильный запрос (например, разорвать соединение)

**Comment by dzharkov** [comment]
1. Мне не кажется это логичным, поскольку у скачивающей стороны есть информация о размере файла, и определить размер последней части все еще возможно
2. Для этого там и добавлен запрос stat, с помощью которого можно узнать, какие части есть.
   Если такой части нет, то скачивающая сторона нарушила логичные правила использования протокола, и что происходит дальше — undefined behavior
