### ISSUE TITLE
Вопрос -- Клиент как консольное приложение

### ISSUE THREAD

**Issue by LDVSOFT** [java-course-au/assignments-2#54]
Должен ли клиент работать интерактивно, или за раз из параметров командной строки совершать одно действие? Какие действия во втором варианте должен уметь клиент -- непосредственно действия протоколов (скачать такую часть такого файла от такого раздающего) или что-то более высокоуровневое (скачай файл, сам разберись)?

**Comment by dzharkov** [comment]
Каждый запуск приложения — одно действие
Варианты действий:
- list `<tracker-address>`
- get `<tracker-address>` `<file-id>` (в этот момент просто записывается необходимость скачать файл, после чего программа завершается)
- newfile `<tracker-address>` `<path>`
- run `<tracker-address>` (программа бесконечно раздает имеющиеся файлы и скачивает еще не скачанные)

В рамках последней команды нужны также уведомления о скачанных файлах, возможно полезна будет дебажная информация: новый клиент/сид, скачал такую-то часть.

@LDVSOFT примерно понятно?

**Comment by dzharkov** [comment]
Updated

**Comment by LDVSOFT** [comment]
@dzharkov Понятно, реализовывать будет весело) Ещё @tehnar интересовался

**Comment by dzharkov** [comment]
@LDVSOFT А в чем сложность?

**Comment by LizaTretyakova-zz** [comment]
@dzharkov Мне непонятно :)
1. list `<tracker-address>` -- это запрос к приложению-клиенту?
2. get `<tracker-address>` `<file-id>` -- то есть на указанном трекере должна быть сделана запись, что такой-то клиент (то есть мы) хочет такой-то файл? Что после этого должно произойти? Трекер должен послать этому клиенту список адресов, по которым надо стучаться с указанием конкретных файлов? Что, если по этим адресам больше не раздают необходимый кусок (просто сервер ещё не успел узнать)? 
3. run `<tracker-address>` (программа бесконечно раздает имеющиеся файлы и скачивает еще не скачанные) -- то есть программа начинает работать как трекер? Или наоборот, после какого-то числа приготовлений (несколько запросов get к существовавшим трекерам) мы готовы сами стать трекером, качая, наконец, всё те ещё файлы из get-запросов себе и попутно помогая новым клиентам получить их файлы?

**Comment by LDVSOFT** [comment]
@LizaTretyakova 
1. Нет, это запрос к трекеру -- какие файлы трекер знает
2. Нет, трекер не знает, кто какой файл хочет. Всё, что он знает -- какие есть файлы, и кто их раздаёт. Помнить, что клиент хочет скачать -- дело самого клиента.
3. Всё вышеперечисленное относится к программе клиенту. Трекер -- отдельная программа, запущенная отдельно. Подразумевается, что во время работы клиента по указанному `<tracker-address>` будет работает трекер.

**Comment by LizaTretyakova-zz** [comment]
@LDVSOFT @dzharkov 
Но из всех указанных действий я не вижу, чтобы хоть где-то клиент таки получал свой файл. Он его то просит, то анонсирует хранение, то ещё что-то -- но нигде не описан процесс скачивания.

**Comment by dzharkov** [comment]
@LizaTretyakova get `<tracker-address>` `<file-id>` (в этот момент просто записывается необходимость скачать файл, после чего программа завершается)
После этого клиент запускается с параметром `run` и скачивает _все_ до этого нескачанные файлы, одновременно раздавая уже имеющиеся части.

**Comment by LizaTretyakova-zz** [comment]
@dzharkov 
А, значит, механика такая: приложение объявляет(и запоминает у себя внутри) некоторый список файлов, которые хочет получить, а потом запускается на run, после чего его трекер отправляет за нужными частями к каким-то другим клиентам + направляет за имеющимися файлами других клиентов к этому. Вот так должно быть правильно, вроде)

**Comment by dzharkov** [comment]
@LizaTretyakova Все верно
