### ISSUE TITLE
Вопросы про клиента

### ISSUE THREAD

**Issue by LizaTretyakova-zz** [java-course-au/assignments-2#62]
@dzharkov 
1. Правда ли, что list, get, newfile и run относятся к "клиентской" части клиента, а stat и get -- к "серверной"?
2. Правда ли, что "серверная" сторона клиента запускается по команде run?
3. Почему и в run, и в изначальный get передаётся адрес торрент-трекера? Не будет ли достаточно передавать его в какое-то одно место? Иначе для чего это сделано?
4. Правда ли, что нам никогда не нужно задавать клиентский сокет самостоятельно?

**Comment by LizaTretyakova-zz** [comment]
@dzharkov 
Oo

**Comment by dzharkov** [comment]
@LizaTretyakova 
Я почему-то думал, что на эти вопросы ответил на паре :(
1. Я не понял вопрос, у тебя там кажется и команды клиента и типы запросов в нашем протоколе смешаны. К тому же непонятно, что значит <<относятся к "клиентской" части>>.
2. Да, в этот момент открывается слушающий сокет
3. Тогда его придется хранить где-то, предлагаю так не делать. То есть надо реализовать, как написано в issue
4. Не понял вопрос. Кому "нам"? Имелось ввиду создавать? Кто-то это делать должен в любом случае

Еще просьба, если я больше суток не отвечаю на срочные вопросы, дублировать на почту

**Comment by LizaTretyakova-zz** [comment]
@dzharkov 
1. Мм.. Команды stat и get выполняются только при открытом слушающем сокете, запущенном после команды run, в то время как команды list, get, newfile -- в любое время?
3. А, так вот оно что!
4. А, когда по семантике команды нам необходимо открыть клиентский сокет, мы делаем это на произвольном порте и с ним работает, так?

Хорошо, поняла про почту.

**Comment by LizaTretyakova-zz** [comment]
@dzharkov 
И ещё вопрос, появился сейчас: что делать, если у нас во всех описаниях тип порта -- short, при этом номер порта поместится только разве что в unsigned short, но такого в Java, кажется, нет?

**Comment by dzharkov** [comment]
@LizaTretyakova 
1. Ты дважды используешь термин «команда get» во взаимоисключающих частях. Еще раз спрошу, ты имеешь ввиду консольные команды (из https://github.com/java-course-au/assignments-2/issues/54) или виды запросов в протоколе, описанные в Readme?

Если второе, то вроде бы ответ на вопрос, да. Серверные запросы `list, newfile` отправляются только в рамках команд `list, newfile`.
4. Да, выбирается произвольный порт (можно константный), номер которого отправляется на трекер в рамках запроса `update`

Порт 8081 помещается в short.

**Comment by LizaTretyakova-zz** [comment]
Спасибо, теперь всё встало на свои места!
